[alias]

[settings]
experimental = true

[settings.pipx]
uvx = true

[tools]
"pipx:llm" = "latest"
"pipx:xxh-xxh" = "latest"
"pipx:shell-gpt" = "latest"
"pipx:ipython" = "latest"
"pipx:yewtube" = "latest"
"pipx:epy-reader" = "latest"
"pipx:aider-chat[browser,playright]" = "latest"
erlang = "27"
elixir = "v1.17-otp-27"
ruby = "3.2"
zig = "0.13.0"
gleam = "1.5.1"
lazydocker = "0.23"
node = "23"
python = "3.12"
uv = "latest"
"ubi:duckdb/duckdb" = "latest"
